### ISSUE TITLE
Consider using predefined thumbnails for the Libary view instead of those passed by jellyfin 

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#101]
**Describe the bug**
Couldn't reopen #73, library names are repeated in the Library view in the new 0.8.1 release. It looks like the large words are embedded in the image downloaded from Jellyfin, and the smaller is text overlayed on Streamyfin. It also causes overlap for the "Collections" text.

In landscape the image height is too low causing the top and bottom of the words to be cut off.

**To Reproduce**
1. Go to Library, you can see the issue
2. Rotate to landscape and you can see the 2nd issue

**Screenshots**
![IMG_1193](https://github.com/user-attachments/assets/602886d6-8a5c-4445-a30f-47e5f96fae69)
![IMG_1194](https://github.com/user-attachments/assets/d9d4b1c9-d23b-4b54-8ea5-f9a12eb66558)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 17.6.1
 - Version 0.8.1

**Comment by retardgerman** [comment]
That's actually not really a problem with the app. This was also happening to me. Turns out, Jellyfin automatically generates a thumbnail for the library and burns the name of the library into it. That is then also displayed in the app.

Unfortunately, there is no option on jellyfin's side to prevent this if you want to use automatic metadata.

**Comment by yihaolee85** [comment]
> That's actually not really a problem with the app. This was also happening to me. Turns out, Jellyfin automatically generates a thumbnail for the library and burns the name of the library into it. That is then also displayed in the app.
> 
> Unfortunately, there is no option on jellyfin's side to prevent this if you want to use automatic metadata.

Yes, maybe then the small text can be removed? Or do you mean there is a case where it is possible that the thumbnail for the library won't contain the name? If so, maybe we can consider putting the Library name below the thumbnail like how it is for movie posters?

**Comment by retardgerman** [comment]
Maybe we could think about using a pre-selected image for the buttons and not transferring the thumbnail of the library to the buttons. So the small text could be left as it is.

**Comment by yihaolee85** [comment]
Yes, either way works, as they both solve the problem

**Comment by fredrikburmester** [comment]
I don't have the text burned on top of the image, that's why i added the small text.

![IMG_9D401C42F494-1](https://github.com/user-attachments/assets/9d3522b2-9621-4fd7-8a24-1c1108a4d2dc)

Maybe i can check what type of library image is used and render the text accordingly. Gonna investigate.

**Comment by fredrikburmester** [comment]
This is solved in a future release by letting uses choose the look.
