### ISSUE TITLE
Wrong description for Download quality settings

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#112]
**Describe the bug**
Wrong description for Download quality settings

**To Reproduce**
1. Open settings page
2. See text below "download quality"

**Screenshots**
![IMG_1228](https://github.com/user-attachments/assets/9ecd5f73-f304-4e10-a93b-ac667a9877b0)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 17.6.1
 - Version 0.8.4 (5)

**Comment by fredrikburmester** [comment]
Thank you!
