### ISSUE TITLE
Implement quick login for other devices

### ISSUE THREAD

**Issue by mateusz-bak** [fredrikburmester/streamyfin#113]
**Describe the solution you'd like**
Please allow Streamyfin to authenticate other devices to be logged in by using quick connect.

How this would work:
1. User wants to login on a TV, selects quick login  and generates the code.
2. Used goes to Streamyfin's settings and selects "Quick connect"
3. User inputs the code from TV into the app
4. Auth is successful

**Additional context**
I think for now only official android app supports this.

**Comment by fredrikburmester** [comment]
Right, the other way around haha! I just implemented QC to log **into** the app. Will implement in a future release.
