### ISSUE TITLE
Login issue with http (https works)

### ISSUE THREAD

**Issue by m-kronberg** [fredrikburmester/streamyfin#12]
Duplicate of other issues, but people are probably missing the actual problem here.

I can log in with my FQDN with HTTPS normally.
If I try the same server with it's internal IP address ,or it's Tailscale IP address over http, it doesn't work.

I have a root account with no password, and a user account with password, both work as long as I am using a https with my FQDN.

The issue is probably connecting to not secure http.

**Comment by m-kronberg** [comment]
We can probably merge the other issues here.

**Comment by fredrikburmester** [comment]
Thanks for the info! For me it's working over http with my local IP. But i'm gonna investigate some more. Any more testing would be appreciated!

**Comment by fireflypulse** [comment]
Is this Android or iOS specific? I'm not having this issue on iOS using the IP:port with http.
I just got my jellyfin back up and running so I could test this app, so my FQDN isn't setup yet.

**Comment by amarevite** [comment]
Android user here. Only https works for me. Trying to log in over http to the local IP address gives me the following error: `network error occurred. Did you enter the correct server URL?`

**Comment by fredrikburmester** [comment]
This should be fixed in the new release (0.3.1)!
