### ISSUE TITLE
Remove the need to put https and http

### ISSUE THREAD

**Issue by Gauvino** [fredrikburmester/streamyfin#123]
**Describe the solution you'd like**
When entering like DOMAIN.TLD is automatically choose http or https and don't have the need to put `https://DOMAIN.TLD`

**Additional context**
![image](https://github.com/user-attachments/assets/ba95e0a6-f4c7-4401-9381-c6470b2a7bac)

**Comment by fredrikburmester** [comment]
This is highly individual and people might use local addresses or not, sometimes people use plain http even though they use a domain, sometimes people use magic DNS with Tailscale. Therefore i don't think it's a good idea to auto-fill http/s and currently i won't implement this.
