### ISSUE TITLE
Audio doesn't change in direct play

### ISSUE THREAD

**Issue by mgt1309** [fredrikburmester/streamyfin#125]
**Describe the bug**
Have an anime file that has English and Japanese audio. Selecting subtitles to English works. However, selecting Japanese audio does not change the audio

**To Reproduce**
1. Go to settings
2. Enable direct play
3. Go to video with two different audio tracks
4. Select one that isn't the default
5. Audio still outputs default even though secondary track was selected beforehand.

 - Device: Samsung galaxy S21 FE 5G
 - OS: Android 14
 - Version August 1st 2024

**Comment by Alexk2309** [comment]
This issue should be resolved with the new VLC player
