### ISSUE TITLE
Connection via IPv6

### ISSUE THREAD

**Issue by Provider2436** [fredrikburmester/streamyfin#130]
**Describe the solution you'd like**
I want Streamyfin to connect and playback video via IPv6.

**Additional context**
Currently when connecting to the Jellyfin for video playback it only connects via IPv4. I would like to be able to connect only via IPv6.

**Comment by fredrikburmester** [comment]
Hi, i'm sorry but i don't really understand what you mean. Could you please elaborate? Do you mean that the connection string is an IPv6 address? Or that it's somehow related to the video streaming?

**Comment by Provider2436** [comment]
I would like Streamyfin to support video playback over IPv6. Currently, the app connects to my Jellyfin server using only an IPv4 address for video playback, but my server and network are fully set up for IPv6. I'd like the app to either prioritize or exclusively use IPv6 when connecting to the server for video streams, as shown in the attached screenshot where the connection uses an IPv4 address (e.g., 159.69.108.193). To clarify, this is not about the internal streaming protocol (like HTTP or WebSocket) but rather about the network connection between the app and the server. The app currently defaults to IPv4, but I want it to support and utilize IPv6 for these connections.
![Screenshot from 2024-09-18 18-12-32](https://github.com/user-attachments/assets/6c9f08a3-78f9-44c0-8c94-60b7c53572a4)
![Screenshot from 2024-09-18 18-19-12](https://github.com/user-attachments/assets/c295acee-9d92-411c-9a82-d3f50e90421a)

**Comment by Provider2436** [comment]
Okay, I just fixed it. It was my fault, I had to enable enable access to local network in the iOS settings and now it connects via IPv6. Sorry for bothering you. 

I just have to add that your project is one of the best iOS Jellyfin client available, thank you for your work.
