### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by joshjryan** [fredrikburmester/streamyfin#136]
Requesting an Android TV version to be considered for v2.0+.

**Comment by retardgerman** [comment]
Duplicate of #137

**Comment by joshjryan** [comment]
Apologies for not not noticing the existing request. I searched the string "Android TV" and didn't return any results :)

**Comment by retardgerman** [comment]
No worries! We had an internal discussion about merging all "TV related" issues into one. You did nothing wrong.
