### ISSUE TITLE
Home Screen, Continue Watching bug.

### ISSUE THREAD

**Issue by SuperSonicFlea** [fredrikburmester/streamyfin#143]
On the Home Screen when one episode under continue watching it becomes unresponsive after plying and backing out.

On the Home Screen with only 1 item in the continue playing.
1. Open the video and play it. 
2. Cancel playback and go back to Home Screen.
3. No longer able to tap and access video under continue playing without restart of app. 

 - Device: iPad mini and iPhone 12
 - OS: 17.6.1 and 17.7
 - Version 0.15.0

**Comment by fredrikburmester** [comment]
Fixed on master
