### ISSUE TITLE
great but a few additions and it could be incredible

### ISSUE THREAD

**Issue by The-Math-God** [fredrikburmester/streamyfin#146]
Firstly thank you for giving us a jellyfin ios client that doesn't suck
but there are i few features that could make it even better

1. a download on wifi only setting 
this sounds weird but i have remote access to jellyfin 
via a domain name i bought on namecheap 
no joke i used this app for the first time @ my grandmothers today
so a download on wifi only setting would be helpful 
so i don't use up my mobile data

2. background downloads
this one is pretty simple when i was using it 
if my iphone went to sleep the download just stopped

3. a download button for an entire show or at least a season
it can be a pain to download a tv show one episode at a time 
so a download button for an entire show or at least a season 
where all the episodes will be added to the queue 
would be awesome

4. tap the touchscreen to pause, play, rewind, or fast forward. without using the progress bar
its inconsequential i know but its just one of those simple quality of life improvements 

outside of that fantastic job a free jellyfin client that not only downloads 
but can even make transcoded versions for your phone incredible work
thanks to this i have no interest in switching to emby now

**Comment by fredrikburmester** [comment]
I'm gonna close this issue because it's very loose. I love the ideas, but please open separate issues for all feature requests (and make sure no open ones exist that are similar). Thank you!
