### ISSUE TITLE
Remaining time not updating in player

### ISSUE THREAD

**Issue by DasBrin** [fredrikburmester/streamyfin#147]
**Describe the bug**
Remaining time is not updating in the player

**To Reproduce**
1. Play media
2. Look at bottom right

**Screenshots**

https://github.com/user-attachments/assets/938a49c0-4c72-448f-a926-07214e586bfd

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: Android 14
 - Version 0.15.0 PlayStore Release

**Comment by fredrikburmester** [comment]
Fixed on master
