### ISSUE TITLE
Cannot play downloaded file offline...

### ISSUE THREAD

**Issue by MattBlackOnly** [fredrikburmester/streamyfin#150]
**Describe the bug**
When I attempt to play a downloaded file while offline nothing happens and no errors are shown. (Nothing in logs either.)

However if I'm online and attempt to play the downloaded file it works fine.

**To Reproduce**
1. Download file
2. Go offline
3. Attempt to play downloaded file
4. Nothing happens

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 14
 - Version: 0.10.2

**Comment by fredrikburmester** [comment]
This is fixed in a future release!

**Comment by MattBlackOnly** [comment]
Perfect, thanks for you work on this project. It's really appreciated.
