### ISSUE TITLE
Video player doesn't properly hide navigation bar

### ISSUE THREAD

**Issue by ACViper** [fredrikburmester/streamyfin#152]
**Describe the bug**
The navigation bar is hidden, but there is still a black bar. It forces the video to move up, instead of covering the whole screen. 

**Screenshots**
(Not Stretched)
![Screenshot_20241003-001102](https://github.com/user-attachments/assets/0aa61b23-4b2e-48f7-acff-40239519e23e)
(Stretched)
![Screenshot_20241003-001055](https://github.com/user-attachments/assets/50a248e4-dbc0-4f5d-8c14-730d97b4cb9e)

**Smartphone (please complete the following information):**
 - Device: [Pixel 4xl]
 - OS: [e.g. android 13]
 - Version [e.g. 0.15.0]

**Comment by fredrikburmester** [comment]
Thanks, will look into it!

**Comment by MulverineX** [comment]
Adding onto this, on a Pixel 8 Pro, the video gets shoved into the rounded corners of the screen, cutting off the content, which isn't ideal.

**Comment by rlad78** [comment]
Would just like to add that this happens on my Samsung S23 as well; on Android 14, Streamyfin 0.15.0.

Samsung's Android skin has the ability to switch between the "gestures" navigation bar (what the Google Pixels' skins use by default) and the traditional 3-button nav bar. When using the 3-button nav bar, the video player will use the entire screen as expected. In fact, when switching to the 3-button nav bar and playing a video for the first time, a text overlay appeared explaining how the app was in "fullscreen mode" and swiping up would bring back the nav bar (not sure if this is from Samsung or from Streamyfin).

I'm not versed in JS/TS, but if there's any other way I could assist, please feel free to ask.

**Comment by fredrikburmester** [comment]
This should be fixed in the latest release. Please comment if not and i'll reopen!
