### ISSUE TITLE
Don’t show unsupported media (book) in Continue Watching 

### ISSUE THREAD

**Issue by syfq91** [fredrikburmester/streamyfin#155]
**Describe the bug**
Currently the app shows ongoing book in continue watching rows even if it doesn’t support it 

**To Reproduce**
1. Read some book in Jellyfin app. Not Streamyfin. 
2. Open Streamyfin app. 
3. See unsupported media in continue watching row. 

**Screenshots**
![image](https://github.com/user-attachments/assets/4f205dff-114c-4762-85cf-77c8c343098e)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 18.0
 - Version: Testflight 0.16.0 (20)

**Comment by fredrikburmester** [comment]
fixed on master
