### ISSUE TITLE
Chromecast Button Not Doing Much

### ISSUE THREAD

**Issue by alanpaone** [fredrikburmester/streamyfin#159]
**Describe the bug**
When I try to cast media, the chromecast button appears, and lights up in response to touches, but doesn't do anything else, no list of  chromecast targets, etc. 
It seems like this works for most people, am I missing something like a setup step?

**To Reproduce**
1. Go to any screen in the app, main screen, any movie or tv show
2. Click on chromecast button 

**Screenshots**
![Screenshot_20241005-104357](https://github.com/user-attachments/assets/4f1b5c17-5082-4e6b-8cf3-f8e2c8f8705c)
![Screenshot_20241005-104411](https://github.com/user-attachments/assets/08be0d36-99d3-4737-bada-a176eb6b94d2)

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: android 15 (build AP41.240823.009 if it helps)
 - App Version 0.15.0

**Comment by kendoka15** [comment]
Mine worked until today, now it does the same

**Comment by pixyze** [comment]
Same for me.

**Comment by fredrikburmester** [comment]
Could you guys also share your device information @kendoka15 @pixyze ?

**Comment by jakequade** [comment]
I also noticed that the app doesn't chromecast anymore - but for me (iPhone 15) it opens the ExpandedController, and then just spins (app is still responsive, just doesn't load chromecast. I'll do some digging on my fork and see if I can uncover anything.

**Comment by fredrikburmester** [comment]
Thank you, please do @jakequade , this is strange. For me it works like a charm, on but the app store version and the current TestFlight. 0.17.0 will be released in the next days. Maybe that will fix it.

**Comment by faviann** [comment]
Tested the 0.15.0 version from the app store and the 0.17.0 from the GitHub release page and for both the cast button does nothing on my Pixel 8 Pro

I'm on Android 14.

Since I just installed it for the first time today so I'm not sure how if it was supposed to work. Any clue at how I could peek at logs to see if there's some error or timeout or anything else similar?

**Comment by kendoka15** [comment]
> Could you guys also share your device information @kendoka15 @pixyze ?

Sorry for the late response, it's a Pixel 7 running Android 14 with the latest app version

**Comment by pixyze** [comment]
Sorry, it's Xiaomi 11 Lite 5G NE, Android 14.

**Comment by AdnerVL** [comment]
Same issue, cast button don't work
Version 0.17.0
Pixel 7a
Android 14

**Comment by kendoka15** [comment]
v0.18.0 fixed it. Many thanks
