### ISSUE TITLE
if the TV shows title is long enough they overlap in downloads

### ISSUE THREAD

**Issue by The-Math-God** [fredrikburmester/streamyfin#162]
**Describe the bug**
I found a bug for v16
If the shows title is long the overlap

**To Reproduce**
simply download 2 episodes of a tv show with a long title

**Screenshots**
![IMG_1997](https://github.com/user-attachments/assets/302fece6-afac-4782-983c-101547660cc7)

**Smartphone (please complete the following information):**
 - Device: [iphone SE]
 - OS: [iOS 18]
 - Version [16]

**Comment by fredrikburmester** [comment]
fixed on master

**Comment by The-Math-God** [comment]
The same problem is happening but on movies
![IMG_2017](https://github.com/user-attachments/assets/539b1309-b05d-4208-8cd2-0772ecb54d8c)
