### ISSUE TITLE
streamyfin optimized version tries to process the entire queue after the first download

### ISSUE THREAD

**Issue by The-Math-God** [fredrikburmester/streamyfin#167]
**Describe the bug**
hi i noticed an issue with [streamyfin-optimized-version]
when you queue multiple downloads in the queue 
exit and reenter the app after it downloads the first 
it tries to transcode the entire queue
and yes max concurrent jobs are set to 1 

i dont know if this goes here or streamyfin app  
so im adding this to both

**To Reproduce**
1. start multiple downloads in the queue
2. exit the app 
3. wait for the first job to finish 
4. start the app 

**Screenshots**
![thumbnail](https://github.com/user-attachments/assets/140b177e-64b6-4a2e-8d15-916308651cd5)

**Smartphone (please complete the following information):**
Device: [iphone SE]
OS: [iOS 18]
Version [16]

**Comment by fredrikburmester** [comment]
Thank you i'll take a look at it

**Comment by fredrikburmester** [comment]
Closing this one in favor of https://github.com/fredrikburmester/streamyfin-optimized-versions-server/issues/4
