### ISSUE TITLE
Enhancement: Native PiP on iOS

### ISSUE THREAD

**Issue by mobiledude** [fredrikburmester/streamyfin#17]
Love the app, love the energy you put in. I second using your framework to support AppleTV ;-)
This is for future enhancements -> adding native Picture in Picture for iOS and AppleTV, and whle you are at it, the same might apply for Apple watch player controls like pause, play and trickplay.

Keep up the great work and don't become overwhelmed by all enthusiasm, it proofs you have a great app here and doing great stuff!!

**Comment by fredrikburmester** [comment]
Pip for iPhone is now available in the latest release!

**Comment by mobiledude** [comment]
Hi @fredrikburmester , Thank you, but please help me out. There is 2 ways op PiP implementation right?. One is within the actual app? Playing in the small preview window in the player in the bottom of the screen. However some video apps show PiP native in iOS and they are able to keep playing in a small window while being able to use other apps as well. How do I actually activate the latter?

**Comment by mobiledude** [comment]
Wow! amazing!
