### ISSUE TITLE
Simplify logo

### ISSUE THREAD

**Issue by steveiliop56** [fredrikburmester/streamyfin#170]
Hello,

I firstly can't help saying that the app feels amazing and I love it. There is just a tiny thing breaking my OCD, the logo. I would recommend making it simpler because right now it looks like a small wonderland on my home screen lmao.

**Comment by fredrikburmester** [comment]
Did you see the latest release? https://github.com/fredrikburmester/streamyfin/releases/tag/v0.17.0

**Comment by steveiliop56** [comment]
Oh wow that looks awesome, I used the play store version so it wasn't there for me. Anyway closing this.
