### ISSUE TITLE
Previously downloaded items gone after automatic update in ios

### ISSUE THREAD

**Issue by ext4xfs** [fredrikburmester/streamyfin#182]
**Describe the bug**

Previously downloaded items gone after automatic update in ios app updates

**To Reproduce**
1. Go to downloads, see nothing 

**Screenshots**

![IMG_0007](https://github.com/user-attachments/assets/0519979e-d8ee-4694-ae69-c966e5e52698)

![IMG_0008](https://github.com/user-attachments/assets/2274037b-266b-4189-8e68-84abaeacd186)

sad this happened right before 12hrs of travel 😩

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2024
 - OS: iOS 18
 - Version 0.17.0

**Comment by fredrikburmester** [comment]
Sorry this happened to you, we changed the storage keys for items in the app. This app is in early beta and things change rapidly. In the future the downloads will not disappear and this is not an issue.

**Comment by ext4xfs** [comment]
No worries @fredrikburmester, it might be a good idea to show these items or warn however, because the storage was still in use (so I had to delete the app to clear)
