### ISSUE TITLE
Invalid trickplay images (iOS, 20s between images)

### ISSUE THREAD

**Issue by azalty** [fredrikburmester/streamyfin#186]
**Describe the bug**
Shown trickplay images are not the right ones, often showing images that are a few minutes later in the movie or maybe sometimes even more. Tested on iOS on an h264 movie, with 20s between each trickplay frame.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.7
 - Version: 0.17.0

**Comment by fredrikburmester** [comment]
It might be an issue that you have 20s between each frame. I think i initially programmed the trickplay images based on a 10s interval. This should of course adapt based on your settings.

**Comment by Alexk2309** [comment]
This should soon be fixed when the upcoming VLC player is released. Thank you for your patience.
