### ISSUE TITLE
Allow playing downloaded files in VLC

### ISSUE THREAD

**Issue by azalty** [fredrikburmester/streamyfin#189]
**Describe the solution you'd like**
Allowing downloaded files to be played in VLC would be a nice addition. The current implementation of VLC (at least on iOS) doesn't seem to easily allow this.

This poses the question of remuxing, because VLC probably supports more types of media and might not need it.

**Comment by HyperrJedi** [comment]
It seems like VLC will be built in as the player soon. This will probably make downloading the VLC app not necessary or useful (unless someone just prefers the app?). Idk if they're gonna keep the connection to the VLC app since it'll be built into the app.

**Comment by fredrikburmester** [comment]
We will probably keep it in, can't hurt. But yes, VLC will soon be integrated into the app and the need to external players will be no more.

**Comment by Alexk2309** [comment]
VLC is integrated into the app, this issue will now be closed.
