### ISSUE TITLE
Media not loading on iOS

### ISSUE THREAD

**Issue by gmeijers** [fredrikburmester/streamyfin#2]
Media doesn’t load on iPhone 12 mini iOS 17.5.1

Tried via both http and https.

Tells me to try logging out and back in again, but no media loads.

does show up in list of active devices.

**Comment by fredrikburmester** [comment]
Hmm ok, can you try this server: `https://jellyfin-test.fdrive.se`and log in with 
Username: `apple`
Pw: `123456`
@gmeijers

**Comment by gmeijers** [comment]
I can’t login to that server. Nothing happens when I tap Log in.

Tried both WiFi / cellular.

**Comment by fredrikburmester** [comment]
The next release will have better error messages. Then we'll know if it's a credentials issue or a network issue. Check if you have a VPN on and if so turn it off maybe. @gmeijers

**Comment by mobiledude** [comment]
Iphone 13 here. Jellyfin on unraid, behind NGINX Proxymanager and Authentik. I was able to login with Username and Password, App looks slick and  content shows up quickly. However unable to stream any media. Please let us know what kind of Info you need.

**Comment by fredrikburmester** [comment]
@mobiledude can you try the test server i posted about above? try media from that server and see if it works.

**Comment by mobiledude** [comment]
> @mobiledude can you try the test server i posted about above? try media from that server and see if it works.

Tried your server and it worked. Way more responsive than my content on local lan. Could the NPM reverse proxy icm with Authentik be the problem? Also using pi-hole to do dns rewrite. All working fine with Jellyfin/swiftfin and infuse btw.

**Comment by fredrikburmester** [comment]
Yeah if it works with Jellyfin/Infuse/Swiftfin then i would like to make it work for Streamyfin as well... Could be that the specific media on your server needs to be transcoded in my app but not in the other apps for some reason. And that the resulting stream is broken in some way. Please keep testing and see if you can find a video that works maybe? I'm gonna keep investigating as well..  @mobiledude

**Comment by gmeijers** [comment]
@fredrikburmester connecting to your server works fine with the new update! I can browse and play media.

Still the same issue when trying to connect to my own server though.

**Comment by MajorP93** [comment]
I can confirm that this issue exists.

I installed Streamyfin 0.5.1 on my iPhone 14 (iOS 17.6.1) and entered my Jellyfin server address like this "http://my.server.com:8096" (actual FQDN was changed). I am currently not using a reverse proxy and therefore no encryption (yet).

I was able to login and can browse media. When trying to play something, the title gets shown on the "control bar" on the bottom of the screen and there is a spinning wheel that indicates the app is trying to load something. After that nothing else happens.

Both jellyfin and swiftfin work fine with my server address and I can play media in those apps.

If there is any additional information required for troubleshooting this issue I will be happy to provide.

**Comment by alonsoCan01** [comment]
I'm also getting the same error log as @MajorP93. My media runs fine on Swiftfin and Infuse, so I found it odd that Streamyfin was having issues.

When media is selected it starts the load process, but never completes. Once I click the video the play button is crossed out. Then the error is shown in the logs.

**Comment by fredrikburmester** [comment]
**What device are you guys using?** The crossed over play icon means the the video is not compatible with the device. I.e. jellyfin is serving a file in the wrong format. This is because i send a "device profile" to the server so that it can determine what to transcode the file into. @alonsoCan01 @MajorP93

**Comment by alonsoCan01** [comment]
> **What device are you guys using?** The crossed over play icon means the the video is not compatible with the device. I.e. jellyfin is serving a file in the wrong format. This is because i send a "device profile" to the server so that it can determine what to transcode the file into. @alonsoCan01 @MajorP93 

@fredrikburmester I am using an iPhone 14 Pro on IOS 17.5.1

**Comment by fredrikburmester** [comment]
Could you send information about the file you're trying to play? If you want to join the discord we can discuss this in more depth: https://discord.gg/zyGKHJZvv4

**Comment by alonsoCan01** [comment]
Just joined. But, just to keep track, the media is in HEVC format 1080p SDR.

**Comment by MajorP93** [comment]
> Could you send information about the file you're trying to play? If you want to join the discord we can discuss this in more depth: https://discord.gg/zyGKHJZvv4

Device is iPhone 14, file is 1080p HEVC SDR aswell. 1080p H264 SDR also does not work for me in Streamyfin though.

**Comment by fredrikburmester** [comment]
We figured out that some people have turned off transcoding on their servers. Since Streamyfin does not support as many codecs as something like Infuse or Swiftfin it's quite important to have the videos/audio/subs in a supported formats, or turn on transcoding. 

Also, even though a video is H264 SDR, the container might not be supported, mkv for example.

**Comment by gmeijers** [comment]
My ehh.. issue was solved the moment I updated my Jellyfin server to the latest version. 👀
