### ISSUE TITLE
Cannot enter server address

### ISSUE THREAD

**Issue by citizen-123** [fredrikburmester/streamyfin#20]
Pixel Fold - can't select the address input to enter my server address.

**Comment by fredrikburmester** [comment]
Hey, can you expand a bit on this? Do you mean that the keyboard won't show when pressing the field? @citizen-123

**Comment by fredrikburmester** [comment]
Can you try on the latest update? @citizen-123

**Comment by Joshndroid** [comment]
@fredrikburmester i just came here to post the same issue however I observed you listed an update. I updated and was able to enter a server and it logged in as expected.

**Comment by schlubahaus** [comment]
Can confirm, is solved with v0.3.4 (Pixel 4a)

**Comment by fredrikburmester** [comment]
Thanks guys!

**Comment by citizen-123** [comment]
The issue is fixed now. Thanks!
