### ISSUE TITLE
Native Transcoding / Downloading Functionality

### ISSUE THREAD

**Issue by JazoBurbs** [fredrikburmester/streamyfin#201]
First of all, LOVE the rapid explosion of interest here. While existing apps have their perks, there are still a number of gaps to close on what I think are essential features.

Re downloads, while I’m unfamiliar with with the technical requirements, are there any plans to support transcoded downloads without requiring install of streamyfin server?

Keep up the great work!

**Comment by fredrikburmester** [comment]
The default download method actually combines the transcoded HLS stream from jellyfin. Sadly the app has to be open for that to happen, but it allows you to download lower bitrate versions of the video. Does this answer your question or were you referring to something else?

**Comment by JazoBurbs** [comment]
Ahhh. Excellent. So the standalone server is just to activate the background downloads? If so, yes. That’s what I meant. Thanks!
