### ISSUE TITLE
Force direct play is not working.

### ISSUE THREAD

**Issue by tbdcit** [fredrikburmester/streamyfin#203]
**Describe the bug**
The option to force direct play still sometimes leads to the media being transcoded.

**To Reproduce**
 - With force direct play off, find a video that would play transcoded
 - Turn on the settings: "use external player" and "Force direct play"
 - Return to the video 
 - Under the play button it reads "transcoded"
 - Play the video and confirm that the server is actually transcoding

**Smartphone (please complete the following information):**
 - Device: Iphone 13 mini
 - OS:  IOS17
 - Version: 0.18.0

**Workaround**
On the jellyfin server it is possible to disable transcoding for that user. Once transcoding is disabled on the server the label under the playback button indeed reads "direct stream".

**Comment by Alexk2309** [comment]
Hey with the new VLC player you should be able to direct play everything with Max bitrate quality selected
