### ISSUE TITLE
Playback Controls won't hide

### ISSUE THREAD

**Issue by AJigsawnHalo** [fredrikburmester/streamyfin#217]
**Describe the bug**
Playback controls would not hide or disappear when playing media.

**To Reproduce**
1. Click on an episode to watch
2. Media playback starts
3. Playback Controls stay on screen and wouldn't hide.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6A
 - OS: Android 14
 - Version: 0.17.0

**Comment by FalenDemon** [comment]
Same bug.
Smartphone (please complete the following information):
Device: Samsung S24 Ultra
OS: Android 14
Version: 0.18.0

App have all permissions.

**Comment by florent4014** [comment]
Same bug on Android 15 on version 0.18 too.

It seems that there is a sweet spot in the upper left corner where i can manage to hide the UI when tapping multiple times. But then, when UI is hidden i have to click multiple time in that previously said area to show it again.

_Besides that, the app is working as a charm, even if the embedded player is struggling the fact that there is VLC as alternative is very good, keep up the good work._

**Comment by florent4014** [comment]
Super nice, thank you !
