### ISSUE TITLE
Notify apkmirror to include this project

### ISSUE THREAD

**Issue by luochen1990** [fredrikburmester/streamyfin#22]
I want to install Streamyfin on my smart TV, but I found that I can't download the Streamyfin APK on apkmirror. I think I might need to actively inform apkmirror so they can properly include this project

[search result](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=streamyfin&bundles%5B%5D=apkm_bundles&bundles%5B%5D=apk_files)

**Comment by luochen1990** [comment]
Thank you, then upload it and let me try it. I think the difference between an Android-based smart TV and an Android phone should not be that significant (apart from the difference in DPI), at least my jellyfin client works on the TV (except for occasional small bugs)

**Comment by fredrikburmester** [comment]
I sent an APK to apkmirror now. Hopefully they accept and you can try it out. Closing this issue for now.
