### ISSUE TITLE
macOS Compatibility

### ISSUE THREAD

**Issue by SABRE1982** [fredrikburmester/streamyfin#230]
It would be great if the iOS version could run full screen in macOS. Currently it's limited to a mobile screen size.

**Comment by fredrikburmester** [comment]
This is fixed and merged into master. Sadly the bottom tabs does not yet support MacOS, but that's coming soon. I'll close this for now. 

https://okwasniewski.github.io/react-native-bottom-tabs/docs/getting-started/how-is-it-different.html#multi-platform-support

**Comment by SABRE1982** [comment]
Hi,

That's great news. Unfortunately, which I assume is related to the bottom tabs issue, there's now a side menu which is perpetually displaying across a portion of the interface. I can't seem to close it, so I can't navigate inside of the app.

**Comment by fredrikburmester** [comment]
Exactly. The sidebar is the MacOS look for the bottom tabs library. They need  to support MacOS.
