### ISSUE TITLE
Unresponsive UI in main overview

### ISSUE THREAD

**Issue by fscorrupt** [fredrikburmester/streamyfin#239]
**Describe the bug**
Attached is a video showing how the UI becomes unresponsive. However, this issue seems to occur only on the main overview and in the library. As soon as I navigate to an item, the UI becomes responsive again.

**Smartphone (please complete the following information):**
 - Device: Samsung S23 Ultra
 - OS: Android 14
 - Version: 0.21.0 (and earlier)

https://github.com/user-attachments/assets/444dc815-0fd6-4e8d-a8f6-9ac78c16f8b1

**Comment by fredrikburmester** [comment]
Thanks for this! 

Maybe we're rendering too many items? Can you scroll horizontally and check how many items are in those lists?

**Comment by fscorrupt** [comment]
hey, about 50 per lib, i have 13 libs, so a lot to render.

**Comment by fscorrupt** [comment]
sounds good :)
