### ISSUE TITLE
Better UX for Playback Controls

### ISSUE THREAD

**Issue by tom-heidenreich** [fredrikburmester/streamyfin#244]
**Describe the solution you'd like**
The Playback Controls should be easier to use, by making buttons larger and adding more space between them.
If the current design is intended to be this way, maybe add an option to change the design.

**Additional context**
The findroid Playback Controls could be a good inspiration.
![Screenshot_20241203_175840_Findroid](https://github.com/user-attachments/assets/ae9756d2-4374-46ca-b866-c98b3953c568)

**Comment by Alexk2309** [comment]
@tom-heidenreich Please have a look at #248 are you happy with these UI changes? If so I can close this ticket.

**Comment by tom-heidenreich** [comment]
Yes, this looks great
