### ISSUE TITLE
[iOS] Login Error Before Local Network access given

### ISSUE THREAD

**Issue by ebits21** [fredrikburmester/streamyfin#28]
Small issue.

On iOS, the app asks for local network access the first time logging into a server.

Before access can be granted, the login gives an error and the user has to hit enter a second time after giving network permission.

I think the error checking needs to wait to see if local network access has been given before giving an error. When access is given, the original login should continue without entering the password again.

**Comment by fredrikburmester** [comment]
Local network access is only necessary for chromecast (or so i thought), and shouldn't have anything to do with connecting to a Jellyfin server. Are you sure that you could not connect to your Jellyfin server before allowing local netowrk access? @ebits21

**Comment by norahqueen** [comment]
> Yeah if I turn off local network access in permissions now it can't connect to the server.
> 
> It should require it to access a local server no?

ebits is right. I get asked for local network access by most (if not all) apps that access self-hosted services. Even something like the LIFX app to access your smart bulbs needs that permission.

**Comment by fredrikburmester** [comment]
This should be fixed in the latest release. The prompt now opens immediately when opening the app for the first time. Can you guys try it and see if it works?

**Comment by norahqueen** [comment]
> This should be fixed in the latest release. The prompt now opens immediately when opening the app for the first time. Can you guys try it and see if it works?
works now

**Comment by ebits21** [comment]
Yep works 😎
