### ISSUE TITLE
[iOS] HEVC media be seems not to work; chromecast loads something, but media doesn't play.

### ISSUE THREAD

**Issue by abuettner93** [fredrikburmester/streamyfin#3]
Having issues with the iOS app - h264 media loads fine but my HEVC media doesn't. Seems to hang while trying to load. 

Also, chromecast seems to be loading something on the screen (changes when I cast to it), but after that nothing happens. No app loads, and no media is broadcast.

**Comment by meme1337** [comment]
Experienced same issue: audio plays (in this case it was an aac track), video doesn’t (hevc sdr)

**Comment by fredrikburmester** [comment]
What phone are you on? iOS/Android and version number. @meme1337 and @abuettner93

**Comment by meme1337** [comment]
> What phone are you on? iOS/Android and version number. @meme1337 and @abuettner93

Sorry, my bad. 

iPhone 12
iOS 17.5.1

**Comment by abuettner93** [comment]
> What phone are you on? iOS/Android and version number. @meme1337 and @abuettner93 

iPhone 13
iOS 17.5.1

**Comment by fredrikburmester** [comment]
Hi, there's been a couple of updates. Could you please try again with the new version? Both chromecast and normal streaming.

**Comment by abuettner93** [comment]
I don't know what kind of magic you did... but both issues are resolved! 
Casting is working smoothly now (though I think subtitles aren't working - will investigate further tonight, and if so, I'll submit a new bug report). 

I'm also able to play my HEVC media now! Great work!
