### ISSUE TITLE
[android] App will not connect 

### ISSUE THREAD

**Issue by Sammeeeeeeee** [fredrikburmester/streamyfin#31]
**Describe the bug**
After putting in the address (I have tried IP address and FQDN), and inputting the correct username and password, It does nothing. 

I have verified it is working from other apps on my device.

**To Reproduce**
1. Enter server address
2. Enter credentials
3. Click login
4. Nothing happens

**Screenshots**

https://github.com/user-attachments/assets/5191b9c2-13a4-492f-b5e8-98e3be81451e

**Smartphone (please complete the following information):**
 - Device: [s23 ultra]
 - OS: [OneUI 6.1, android 14, sec patch July]
 - Version [e.g. 0.3.3]

**Comment by Sammeeeeeeee** [comment]
I found the issue. Even though it seems like it adds `http://` for you, it only works if you add it yourself.

**Comment by fredrikburmester** [comment]
Ah thank you. Will fix right away.

**Comment by schlubahaus** [comment]
Try adding a port. Adding http:// and a port worked for me.

**Comment by fredrikburmester** [comment]
Yeah the format should be http://IP:PORT for everyone running a local server. Or https://domain.com for people using a reverse proxy.
