### ISSUE TITLE
[Feature] Add download size to offline media downloads

### ISSUE THREAD

**Issue by abuettner93** [fredrikburmester/streamyfin#32]
**Describe the solution you'd like**
A small total file size underneath  or beside the episode number on the offline media/downloaded page. 

**Additional context**
This would be helpful to better understand how large each downloaded file is, and allow users to remove media depending on how much space it takes up. 

This isn't urgent, but would be a feature similar to those in Netflix, etc to allow for users to manage their downloads accordingly. Thanks!

**Comment by fredrikburmester** [comment]
Sounds like a good idea!

**Comment by Schaka** [comment]
For selected bitrate, you'd probably have to indicate that this is a guess.

**Comment by fredrikburmester** [comment]
@Schaka he means after the content is downloaded. Don't have to guess, just check the file size of the downloaded file.
