### ISSUE TITLE
chapters in videos

### ISSUE THREAD

**Issue by rithask** [fredrikburmester/streamyfin#34]
**Describe the solution you'd like**
show a list of chapters in that video

**Additional context**
these are screenshots from Swiftfin iOS app

<img width="774" alt="image" src="https://github.com/user-attachments/assets/0281ece7-865b-4cb1-a99c-77daecbb7c04">
<img width="774" alt="image" src="https://github.com/user-attachments/assets/ba5e345c-45d9-4286-81e2-8893eb4407b8">

**Comment by fredrikburmester** [comment]
Trickplay images and included in the latest release and chapters wont be supported
