### ISSUE TITLE
Always download external subtitles for offline downloads 

### ISSUE THREAD

**Issue by PCJones** [fredrikburmester/streamyfin#35]
**Describe the solution you'd like**
If a user downloads a movie or episode all available external subtitles should be downloaded. Alternatively, or at a later stage, there could be a setting where the user can enable specific languages that should always be downloaded if available

**Additional context**
Currently, after downloading something, you can only use internal subtitles if you selected them before downloading. External subtitles should always be downloaded as they take negligible disk space and should never require transcoding (at least if they are in .srt format). At the moment there is no way to use external subtitles when watching downloaded files.

**Comment by retardgerman** [comment]
Sry, my bad. Shouldn’t edit the roadmap on my phone with touch lol

**Comment by fredrikburmester** [comment]
closing in favor of #56
