### ISSUE TITLE
Allow skipping to the next episode

### ISSUE THREAD

**Issue by PCJones** [fredrikburmester/streamyfin#39]
**Describe the solution you'd like**
When playing a specific episode of a show (e.g. S01E01) there should be a button (which already exists, but is not usable) to skip to the next episode (S01E02) within the player.

**Comment by fredrikburmester** [comment]
It's not possible within the player since the player does not support those type of buttons, but I did add next and previous episode buttons to the page itself!

I'll keep exploring other ways to add buttons within the player, as I agree that would be better.
