### ISSUE TITLE
Change the logo when opening the app

### ISSUE THREAD

**Issue by KomGiann** [fredrikburmester/streamyfin#43]
**Describe the solution you'd like**
Don't get me wrong , but the logo and name is all right . Only the purple screen with the logo in the center when opening the app seems wrong , it makes the app feel "cheap" and "amateurish" with no offence to the code writer. By deleting this or customising a bit the app would be perfect 

**Additional context**

**Comment by fredrikburmester** [comment]
What would you like to see instead? Do you have any examples or other apps we can look at for inspiration? @KomGiann

**Comment by KomGiann** [comment]
Maybe you don't need an opening screen . Or do it with a way to minimise the attention by the user , like a different more white or black shade to the purple . Also logo seems big and highlighted I would suggest to lower the brightness of this one

**Comment by fredrikburmester** [comment]
If you could sketch up an example in figma (or similar) that would be great!

**Comment by jakequade** [comment]
Idk man you can't really say something looks "cheap and amateurish ... no offence" and it not be offensive - it's still offensive, you were being offensive. 

The app looks great. If it's just your opinion, it probably shouldn't be posted as an issue @KomGiann

**Comment by Hutch79** [comment]
I wouldn't say that the startup screen looks cheap.
On my iPhone 12 pro it opens up way too fast to give it a proper look.
Also, the look and feel of the app itself is way more important than a startup screen. And the App is just gorgeous!

I would argue that the logo is a special one for an app, normally logos are simple so you can remember them easily.
It has lots of details which is not often seen on App Icons.
But who can define "normal", and maybe it was the goal to create something out of the norm.

**Comment by fredrikburmester** [comment]
We have talked about changing the logo, but other more important issues/features have been prioritized.

**Comment by Shah-do** [comment]
Tried to make a simpler logo for Streamyfin, although I wouldn't say I am particularly good at it
![Streamyfin Logo](https://github.com/user-attachments/assets/08fc04f6-d5cf-4529-bea8-de5b7573e2d5)
![Streamyfin](https://github.com/user-attachments/assets/5eae5b22-f887-48f0-91f9-14d20547a415)

**Comment by fredrikburmester** [comment]
I think that logo looks very good! We have another logo in the works as well. We're probably gonna do a poll in the Discord in the near future.

**Comment by Shah-do** [comment]
That sounds great. If any changes regarding colours and such are needed, I'll be happy do so.
