### ISSUE TITLE
Chromecast has no support for subtitles

### ISSUE THREAD

**Issue by abuettner93** [fredrikburmester/streamyfin#44]
**Describe the bug**
When casting, the media plays, but there are no controls to enable subtitles. When playing locally, I can adjust subtitles, but not via chromecast. 

**To Reproduce**
1. Cast media
2. There are no subtitles controls

**Smartphone:**
 - Device: iPhone 13
 - OS: iOS 17.5.1
 - Version 0.4.1

**Comment by abuettner93** [comment]
For what it's worth, I think if the extended controls for Chromecast are added, they come with CC controls automatically. So with any luck, this issue may be moot once that issue is resolved!

**Comment by abuettner93** [comment]
This one should be closable too now that PR 106 is merged!

**Comment by fredrikburmester** [comment]
So subs on chromecast works for you now?

**Comment by Gauvino** [comment]
> So subs on chromecast works for you now? 

For me now subtitles work's great without problem and the control for the chromecast work's also really great thanks !
