### ISSUE TITLE
Chromecast has no scrubbing controls

### ISSUE THREAD

**Issue by abuettner93** [fredrikburmester/streamyfin#45]
**Describe the bug**
When casting, the media plays, but there are no controls to scrub forward or backward once the media is playing. 

**To Reproduce**
1. Cast media
2. There are no scrubbing controls

**Smartphone:**
 - Device: iPhone 13
 - OS: iOS 17.5.1
 - Version 0.4.1

**Comment by fredrikburmester** [comment]
There are no controls on the phone, but there are controls on the TV if you want to scrub. This is due to the extended controls being off in the library i'm using. I've asked for an easier way to turn them on here: https://github.com/react-native-google-cast/react-native-google-cast/issues/538

**Comment by abuettner93** [comment]
@fredrikburmester would this be something to consider? Or is it unrelated to your implementation? https://react-native-google-cast.github.io/docs/components/ExpandedController

**Comment by fredrikburmester** [comment]
Yes i've looked into, and tried, the expanded controller. Though it requires native code. That's fine, but i've asked them to include that code via an expo plugin config here: https://github.com/react-native-google-cast/react-native-google-cast/issues/538

I could include the expanded controller regardless, but it's more for me to manage.

**Comment by jakequade** [comment]
Have put up a PR with the expanded controller implemented, it's an option for the meantime https://github.com/fredrikburmester/streamyfin/pull/106

**Comment by MajorP93** [comment]
+1 I would also really love to see Chromecast controls getting added to the app! 

Thanks for the great work btw :-)

**Comment by abuettner93** [comment]
Saw that the new full controls were pushed as a release! They work great and really make the casting experience 1000x better. Thanks for all the hard work guys! 
I'll leave the ticket for you to mark as closed, yeah?
