### ISSUE TITLE
Hitting the play button only brings up a very small video player

### ISSUE THREAD

**Issue by mholt** [fredrikburmester/streamyfin#47]
**Describe the solution you'd like**
When I play a video, the video should not be a small window at the bottom. It should be full screen or at least full-width.

**Additional context**
Tapping the tiny video does bring it up, but it should do that by default. Tapping the title next to it just slides in the same screen over the current one, making Back more tedious.

----

Really excited about this project, please keep up the good work!!!

**Comment by fredrikburmester** [comment]
Hi, it's a preference thing. I like it when it starts small, but some people like when it goes auto fullscreen. Maybe I can make it an option!

**Comment by mholt** [comment]
Interesting. What's the appeal of it starting small (too small to see)? Maybe I'm missing something.

**Comment by fredrikburmester** [comment]
Sometimes a video takes a couple of seconds to load. In that time I can read about the movie or check other things, like next episodes or ratings or whatever. And when the video has started playing and all intros are done i can open the full player and start watching. And if I do want to start watching immediately i can just press the small player to open full screen.

But i've now built in an option to open full screen immediately. 

<img width="452" alt="Screenshot 2024-08-14 at 18 06 00" src="https://github.com/user-attachments/assets/dd4d8a22-d124-4034-b4e4-93a72873c4c1">

**Comment by mholt** [comment]
> Sometimes a video takes a couple of seconds to load.

Ah, gotcha. That makes sense; but what if it came up automatically when it starts playing?

The option to toggle it is great though, thank you! That was fast.
