### ISSUE TITLE
Oops! Something went wrong. (message after login)

### ISSUE THREAD

**Issue by reedstrm** [fredrikburmester/streamyfin#48]
**Describe the bug**
After successfully authenticating against my Jellyfin server (verified in jellyfin server logs), I see the spinning icon, then the message:
Oops!
Something went wrong.
Please log out and in again.

No additional activity in the server logs. No logs available in streamyfin.

Logging out and in again does the same thing.
**Smartphone (please complete the following information):**
 - Device: Pixel 8a
 - OS: Android 14
 - Steamyfin version 0.4.2
 - Jellyfin server version 10.8.12 

Next steps? Is there a minimum Jellyfin server version? How do I turn on in app logging? I do have access to adb and logcat, though nothing obvious appeared in that log.

**Comment by fredrikburmester** [comment]
Try my test server and see if it works. Could be that you are running an old server version.
Domain: `https://jellyfin-test.fdrive.se`
User: `apple`
Pw: `123456`

**Comment by reedstrm** [comment]
Ok that popped right up (once I deleted the trailing space my keyboard added to the username). I'll schedule an upgrade slot w/ my family for my local server. If that fixes it, would be good to add the minimum supported server version to the README.

**Comment by fredrikburmester** [comment]
Please open another issue for logging!
