### ISSUE TITLE
No way to change audio or subtitle language

### ISSUE THREAD

**Issue by Fyreek** [fredrikburmester/streamyfin#5]
If I have a file that contains multiple audio tracks or subtitles in different languages, there is no way to change that. At least I can’t find an option for that.
Would be nice if that could be implemented.
The official Jellyfin client for iOS has that.

**Comment by fredrikburmester** [comment]
Yes that is a missing feature as of now. It will be in one of the next releases.

**Comment by sayuop** [comment]
Just to add to this.

On the testflight beta the player allows for enabling subs when streaming directly but does not allow to enable subs when it's downloaded.

Audio is not an option in directplay or downloaded.

**Comment by fredrikburmester** [comment]
There should now be an option to select audio stream. Please see if it works for you. As @sayuop said, subtitles are already selectable if the subtitle is supported in the HLS m3u8 stream.
