### ISSUE TITLE
[Feature] Make Downloaded Episodes collapsible

### ISSUE THREAD

**Issue by simonl169** [fredrikburmester/streamyfin#51]
**Describe the solution you'd like**
When downloading a lot of episodes for one series/season, the download section gets crowded.
Can we make the entries per series/season collapsible?

**Additional context**

**Comment by fredrikburmester** [comment]
Yes this sounds like a good feature. I'll get on it. Do you want it collapsible or open a new page?

**Comment by simonl169** [comment]
Never thought about new pages...
I think I prefer collapsible, but would also listen to the majority
