### ISSUE TITLE
Series are no longer collected but each episode is displayed individually in the library 

### ISSUE THREAD

**Issue by DasBrin** [fredrikburmester/streamyfin#57]
**Describe the bug**

Series are no longer collected but each episode is displayed individually in the library.
Issue appeared with Version 0.6.0

**To Reproduce**
1. Open your Libary "Collection"

**Screenshots**
![Screenshot_20240817-110124](https://github.com/user-attachments/assets/ced9712b-f6ed-4288-9589-c3f998f081f5)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8 Pro
 - OS: Android 14
 - App Version 0.6.0
 - Jellyfin Server/Web Version 10.9.9

**Comment by fredrikburmester** [comment]
Yes sorry this is fixed in the next release.
