### ISSUE TITLE
[Feature] Landscape mode for the entire app + audio/sub selection

### ISSUE THREAD

**Issue by tunitz** [fredrikburmester/streamyfin#6]
Thank you, very kind sir.

I would like to request a couple of stuffs if that's ok

1. Landscape as default, or have a button/setting to change the orientation
2. Allow to select Audio/Subs before playing the video

Thank you again for your work sir.

**Comment by fredrikburmester** [comment]
Audio/sub is enabled in the latest release, rotation is fixed in the next one!
