### ISSUE TITLE
Video issues

### ISSUE THREAD

**Issue by Sammeeeeeeee** [fredrikburmester/streamyfin#64]
Hi,

Wasn't sure if I should put these under bug or issue as it is a mix.

Firstly, thank you very much to the developers, my family and friends LOVE this app.

All these issues are with the actual video player (Android). 

*Bugs: * 
1. Once you click play on a video, it goes to the bar on the bottom. My expectation was for it to immediately enlarge to the full screen player. I can see an option for this in settings, but it does not seem to work.
2. To open the video player full screen, you have to tap the thumbnail instead of anywhere on the bar. Even when on the details page for the video, it reopens that page. I put this under bugs, as even clicking the thumbnail does not always work:
https://github.com/user-attachments/assets/87affdf3-bad1-452e-8bf5-39f694f88cf6
3. In the same note, once you get the the video player it is always portrait, regardless of the device setting. I can see an option for this as well in settings, but this also does not seem to work.

*Feature requests:*

4. Once actually in the video player, it would be cool to have gestures to manage brightness and volume.
5. And this is a request from my partner - a 'lock' option like Netflix, so when playing the video no actions on the screen have any affect.
6. I was going to put PIP mode, but it seems like this has already been brought up in #49. 

Once again, thank so much

**Comment by fredrikburmester** [comment]
All these bugs are now fixed, so i'll close this issue. 

For the feature requests, they are not likely to be implemented but you can use an external player (VLC) for a different streaming experience.
