### ISSUE TITLE
Login on android not possible

### ISSUE THREAD

**Issue by N8-Yue** [fredrikburmester/streamyfin#7]
Hello,
I tried to login in the android app and get a network error. Everything is entered correctly
![Screenshot_20240812_185440_Streamyfin](https://github.com/user-attachments/assets/3c8dba0d-951c-4e5a-93e9-e5a2161ad8e0)

**Comment by AetherVoyager** [comment]
same error for me too on local server , but remote server works fine

**Comment by fredrikburmester** [comment]
Thank you guys i will look into why a local server doesn't work...

**Comment by itsaderm** [comment]
same for me, local server. i tried just the IP and Port and then with http:// but neither worked.

**Comment by fredrikburmester** [comment]
This should be fixed in the new release (0.3.1)!
