### ISSUE TITLE
"Start videos in fullscreen" does not work

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#71]
**Describe the bug**
When "Start videos in fullscreen" toggle is enabled, videos do not start fullscreen

**To Reproduce**
1. Go to Settings
2. Enable "Start videos in fullscreen toggle
3. Go to a movie
4. Press play

Video does not start in fullscreen

**Screenshots**
![IMG_1106](https://github.com/user-attachments/assets/9102c745-c144-495e-9438-52842c190d25)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 17.6.1
 - Version 0.6.1 (4)

**Comment by yihaolee85** [comment]
@fredrikburmester I downloaded 0.6.2 (3) and I'm still seeing the same behavior, not sure if this was part of 0.6.2 (3) or a future release?

**Comment by fredrikburmester** [comment]
A release is technically a release here on GitHub: https://github.com/fredrikburmester/streamyfin/releases @yihaolee85

**Comment by yihaolee85** [comment]
@fredrikburmester thank you. Apologies I'm not familiar with the process, just to be clear, downloading a new version on Test Flight is not considered a release until it's on the release page? This will help me understand when to correlate/test if the fixes work on my phone.
