### ISSUE TITLE
TV Shows in collections displays the show, season, and episodes as individual items

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#74]
**Describe the bug**
When a TV show is added to a collection in Jellyfin, the show, season and all episodes are listed in the collections view. Only the TV show should be listed like how it is in the Jellyfin web UI.

**To Reproduce**
1. In Jellyfin, add a TV show to a collection
2. In Streamyfin click on Library
3. Click on Collections
4. Click on a collection item as per step 1

**Screenshots**
![IMG_1088](https://github.com/user-attachments/assets/07702ad1-e71d-4c95-bea9-d9e7dd798955)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 17.6.1
 - Version 0.6.1 (4)

**Comment by fredrikburmester** [comment]
This should be fixed in the next release

**Comment by gianlucaalfa** [comment]
I use 0.24 on Android and I am still affected by this
Thank you
