### ISSUE TITLE
Navigation bug in collection

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#77]
**Describe the bug**
Page navigation is not checked for bounds in collection view, allowing to navigate beyond the last page. Maybe possible to implement infinite scrolling like the Movie view.

**To Reproduce**
1. Go to Library
2. Click on Collections
3. Select a collection
4. Click on the right arrow

**Screenshots**
![IMG_1108](https://github.com/user-attachments/assets/612d4641-c2e7-42ae-adfc-7e375eaabe91)
![IMG_1109](https://github.com/user-attachments/assets/307947ce-a375-4440-a59e-430fa63fd042)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 17.6.1
 - Version 0.6.1 (4)

**Comment by fredrikburmester** [comment]
Thank you for this! Infinite scrolling will be good i think.

**Comment by fredrikburmester** [comment]
fixed in the next release 👍🏻
