### ISSUE TITLE
Unable to cast

### ISSUE THREAD

**Issue by Sheephog** [fredrikburmester/streamyfin#8]
![Screenshot_20240812_182222_Streamyfin](https://github.com/user-attachments/assets/ed865ee8-daf2-4d35-840b-3a18dd8ab41a)
Select casting device, device loads up with cast symbol on screen. Play media, media plays locally.
Using s23 ultra
Anything else please ask

**Comment by fredrikburmester** [comment]
Thank you I will look into it right away.

**Comment by fredrikburmester** [comment]
A fix is coming in the next version!

**Comment by fredrikburmester** [comment]
This should be fixed in the new release, but i've noticed a crash on old android devices. Please test and see if it works! @Sheephog

**Comment by Sheephog** [comment]
How can i check the crash for you? haven't noticed any crashes but haven't extensively used yet. Casting now seems to work, however only if you select cast, then the media to play, if you're already playing media, then select cast, it will not cast, you have to stop the media and start it again.
Thanks again!

**Comment by fredrikburmester** [comment]
Amazing! Great that it works for you. On my device "system ui" keeps crashing when casting. If you have any other android devices you can test with that might be good.
