### ISSUE TITLE
The screen is pretty cluttered when you access a content

### ISSUE THREAD

**Issue by iPleyGit** [fredrikburmester/streamyfin#80]
The screen appears quite cluttered when accessing content information. The back button feels odd to use on iOS. The download, watched, play, etc. buttons should be directly below the cover art. Audio and subtitle selections should be displayed in a way that takes up more space so they're visible without expanding the tab. The play button shouldn't display the content duration and should simply switch between play and resume. The duration information should be shown outside of the play button.

Just take these as suggestions, not rules! Thanks for all your effort. The app is awesome!

![image](https://github.com/user-attachments/assets/77fbd3b3-98bf-49d6-bae0-f6410e208239)

**Comment by fredrikburmester** [comment]
Closing this since we're updating the design a lot. If you feel like you want improvements to the current design feel free to open a new issue with specific requests.
