### ISSUE TITLE
Sorting preference is global instead of per-view

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#84]
**Describe the bug**
As a result of fixes for #75 and #77, sorting in one view affects the sort order in other views.

**To Reproduce**
1. Go to Movies, sort by Community Rating, Descending
2. Go to Collections, sort by Name, Ascending
3. Go back to Movies, they are now sorted by Name, Ascending instead of Community Rating Descending.
4. Similarly, due to fix for #75, entering any collection and backing out to other views will cause them to be sorted by Date.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 17.6.1
 - Version 0.6.2 (3)

**Comment by Shah-do** [comment]
I agree would like sorting to be permanent as well
