### ISSUE TITLE
Better description for common errors during log in

### ISSUE THREAD

**Issue by yihaolee85** [fredrikburmester/streamyfin#87]
**Describe the solution you'd like**
When logging in with wrong username or password, the error message displayed on UI is "Request failed with status code 401". A more user friendly message would be "Invalid username or password"

I'm not sure what are the standard error codes that the Jellyfin server will return, but some common codes that could have better messaging that I can think of:
401 Unauthorized: "Invalid username or password"
403 Forbidden: "User does not have permission to log in"
408 Request Timeout: "Server is taking too long to to respond, try again later"
429 Too Many Requests: "Server received too many requests, try again later"
500 Internal Server Error: "There is a server error"

**Additional context**
![screenshot](https://github.com/user-attachments/assets/9f13c42f-4136-4265-821c-c5180f7f4252)

**Comment by Stooovie** [comment]
I'm getting 401 even with correct credentials. The same (copy/pasted) can be used with other Jellyfin apps without any issues, but Streamyfin errors out with 401

**Comment by fredrikburmester** [comment]
@Stooovie what app version are you on? Did you forget the http part?
