### ISSUE TITLE
Getting 401 error even with correct credentials. Cannot log in

### ISSUE THREAD

**Issue by Stooovie** [fredrikburmester/streamyfin#90]
I'm unable to log into my server (JF 10.9.8 behind Nginx proxy server using http), getting error 401. URL is correct, login and password as well. No issues with other Jellyfin apps. I did quadruple check the credentials, 401 even with copy/pasted URL and credentials. 

I CAN log in with the local LAN address (192.168.), not with the public http://jellyfin.MYDOMAIN.cz address. Again, no such issue with official Jellyfin app, Infuse, Swiftfin or Finamp.

**Comment by fredrikburmester** [comment]
What app version are you on? Did you forget the http part?

**Comment by Stooovie** [comment]
the latest from Testflight, 0.6.2 (3). I did not forget http://, that wouldn't let me enter the credentials.

**Comment by retardgerman** [comment]
Are you sure, your public domain also runs on http and not http(s)?

**Comment by fredrikburmester** [comment]
Hi, can you try on the latest version 0.8.1 when you have access to it and see if the issue is still there. It might be because you are using http with a public domain, which is not advisable.

**Comment by Stooovie** [comment]
Good, it's working! And yes I'll change to https on my server.
