### ISSUE TITLE
Laggy scrolling in the library

### ISSUE THREAD

**Issue by iPleyGit** [fredrikburmester/streamyfin#91]
**Describe the bug**
When scrolling through the entire library, the scrolling experience can be somewhat jerky, especially when loading more items. I wonder if preloading items before reaching the end would improve the smoothness of infinite scrolling.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro max
 - OS: IOS 17.5.1
 - Version 0.6.2

**Comment by fredrikburmester** [comment]
If you could, please send a screen recording.
