### ISSUE TITLE
Empty Libary since 0.6.1

### ISSUE THREAD

**Issue by DasBrin** [fredrikburmester/streamyfin#97]
**Describe the bug**
Libarys are not populated. Just a black page.
Collections work and are not affected, so is the search.

**To Reproduce**
1. Click Libary Button
2. Select Library 
3. Empty

**Screenshots**
https://youtu.be/WaoWNKzlWLM

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: Android 14
 - Version: 0.6.1 ; 0.8.1

**Comment by fredrikburmester** [comment]
Please show me how your jellyfin web looks like and what libraries you have there.

**Comment by DasBrin** [comment]
Web: https://youtu.be/TXtG1G_5Q_I

Send Test Account in DM's
